### ISSUE TITLE
wrong command

### ISSUE THREAD

**Issue by su8** [metinUr/dotfiles#1]
shouldn't be this set to change light ? 

https://github.com/metinUr/dotfiles/blob/c6ca92dbb0da5a065c99fc358a75a182d5228b94/opt/bin/set-light#L18

**Comment by Mr-1311** [comment]
No, it's for show which parameter can program take when you run the program without parameter.

Here is output when you run program without parameter
```
volume <command>
            up
            down
```
So program take 'up' or 'down' parameter and increase or decrease brightness 5% using [light](https://aur.archlinux.org/packages/light/) and send-notify.

I'm using this with keybinding where I set on rc.xml.

**Comment by Dentrax** [comment]
@metinUr I assume he meant it: 

instead of;

`printf "volume <command>\n"` 

must be such;

`printf "light <command>\n"`

Because the light function pertain to the `set-light` script.

**Comment by Mr-1311** [comment]
Oh I see now. I should be more carefully when copy and paste my another script. Changed to light now. :)) thanks.
